In [69]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()
import numpy as np
aArray = np.array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])
print("aArray original shape ...\n", aArray)

reshape1 = aArray.reshape(2, 3, 2)
print("\n reshaping aArray ...\n", reshape1)

aArray original shape ...
 [31 32 33 34 35 36 37 38 39 40 41 42]

 reshaping aArray ...
 [[[31 32]
  [33 34]
  [35 36]]

 [[37 38]
  [39 40]
  [41 42]]]


In [70]:
# 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
import numpy as np
lin_array = np.linspace(0, 20, num=6)
print("Array b ...", lin_array)

Array b ... [ 0.  4.  8. 12. 16. 20.]


In [8]:
# 9. Make a Deep Copy of the above array
import copy
bArray = [ 0, 4, 8, 2, 16, 20 ]
zArray = copy.deepcopy(bArray)

print("The bArray ...\n", bArray)
print("\nThe cArray ...\n", bArray)

The bArray ...
 [0, 4, 8, 2, 16, 20]

The cArray ...
 [0, 4, 8, 2, 16, 20]


In [9]:
# 10. Using NumPy, 'broadcast' the multiplication of the following 2 arrays below to a 2-D array using the newaxis parameter ...
from numpy import array, newaxis

aa = array([0.71, 0.1, 0.24, 0.3])
bb = array([0.8, 0.59, 1.0, 1.11])

print("The sum of aa and bb ...\n")
print(aa[:,newaxis] + bb)




The sum of aa and bb ...

[[1.51 1.3  1.71 1.82]
 [0.9  0.69 1.1  1.21]
 [1.04 0.83 1.24 1.35]
 [1.1  0.89 1.3  1.41]]


In [13]:
# 11. Concatenate these 3 arrays into a new array named 'newArray'..
import numpy as np
array1 = np.array ([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

array4 = np.concatenate((array3, array1, array2), axis=0)
print("\nAnd array4 ...\n", array4)

# 12. Sort 'newArray' in order into 'sortedArray'
arrayCSsort = np.sort(array4)

# print ("\narray4 sorted ...\n", arrayCSsort)

# 13. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
reshapedarray = arrayCSsort.reshape(2, 2, 3)
# print ("\nreshappedarray ...\n", reshapedarray)



And array4 ...
 [[ 7 81]
 [ 5  6]
 [11 12]
 [25 16]
 [11  2]
 [13  4]]


In [18]:
# 14. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables

import numpy as np
tt = ([ [ [7, 81], [5, 6] ],
        [ [11, 12], [25, 16] ],
         [[11, 2], [13, 4]] ])

a, b, c = tt

print("a = ", a)
print("b = ", b)
print("c = ", c)
print("The data type of c ...", type(c))

a =  [[7, 81], [5, 6]]
b =  [[11, 12], [25, 16]]
c =  [[11, 2], [13, 4]]
The data type of c ... <class 'list'>


In [23]:
# 15. Combined and sort the following arrays into one called 'comboArray' ..

from numpy import array
one = array([10, 11, 12, 13, 14, 15, 16, 17])
two = array([20, 21, 22, 23, 24, 25, 26, 27])
three = array([ 0, 1, 2, 3, 4, 5, 6, 7])

arrCombo = np.concatenate((one, two, three))
print("Print arrCombo ...", arrCombo)

arrayCSsort = np.sort(arrCombo)
arrCombosort = np.sort(arrCombo)
print("arrCombo ...", arrCombosort)

Print arrCombo ... [10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
arrCombo ... [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [6]:
#16. Take 'comboArray' and perform the following slicing activities:
import numpy as np
arrCombo = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27])
print("\nThe arrCombo array ...", arrCombo)
# a. print sec1 - the 2nd element
sec1 = arrCombo[1]
print("sec1 element [1] ...", sec1)

# b. print sec2 - all elements from the 3rd element to the last
sec2 = arrCombo[2:]
print("sec2 element [2:] ...", sec2)

# c. print sec3 - all elements from the 4th to the 14th elements
sec3 = arrCombo[3:15]
print("sec3 element [3:15] ...", sec3)

# d. print sec4 - the last 6 elements
sec4 = arrCombo[-6:]
print("sec4 element [-6:] ...", sec4)

# e. print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end
sec5 = arrCombo[-24:-10]
print("sec5 element [-24:-10] ...", sec5)

# f. print sec6 - from #20 every even element to the end
sec6 = arrCombo[16::2]
print("sec6 element [16::] ...", sec6)

# g. print sec7 - from the last element moving forward, every 5th element.
sec7 = arrCombo[::-5]
print("sec7 element [::-5] ...", sec7)




The arrCombo array ... [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec1 element [1] ... 1
sec2 element [2:] ... [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3 element [3:15] ... [ 3  4  5  6  7 10 11 12 13 14 15 16]
sec4 element [-6:] ... [22 23 24 25 26 27]
sec5 element [-24:-10] ... [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
sec6 element [16::] ... [20 22 24 26]
sec7 element [::-5] ... [27 22 15 10  3]


In [54]:
# 17. Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --
import numpy as np
array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

array2 = np.array([[17.0, 70.0, 10.7]])

array3 = np.add(array1, array2)
print("\nAddition ...\n", array3)

array4 = np.multiply(array1, array2)
print("\nMultiplication ...\n", array4)

array5 = np.divide(array1, array2)
print("\nDivision ...\n", array5)



Addition ...
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

Multiplication ...
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]

Division ...
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]


In [55]:
# 18. Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7
import numpy as np

array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

array2 = np.array([[17.0, 70.0, 10.7]])

array6 = np.subtract(array1, array2)
print("\nSubtraction ...\n", array6)


Subtraction ...
 [[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]


In [56]:
# 19. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.
import numpy as np
array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

divisible_by_3 = array1[array1 % 3 == 0]
print("dataarray1 elements divisible_by_3 ...", divisible_by_3)

data2 elements divisible_by_3 ... [ 0.  0. 30. 24. 15.]


In [57]:
# 20. Using Series to create a DataFrame
import pandas as pd

Ingredients = pd.Series(["Flour","Milk","Eggs", "Spam"], name='Ingredients')
Quantity = pd.Series([4, 1, 2, 1], name='Quantity')
Unit  = pd.Series(["cups", "cup", "large", "can"],name='Unit')

df = pd.concat([Ingredients,Quantity,Unit],axis=1)
print(df)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [83]:
# 21. Take this data and create a DataFrame named studentData
import pandas as pd
studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']})
df = pd.DataFrame(studentData)

print(df)

# 22. Add a new column to the DataFrame with the following deserts
deserts_choice = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
df["deserts_choice"] = deserts_choice
df.head()



      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


Name  Height Qualification  address  Age        Pets           sport   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

  deserts_choice  
0      ice cream  
1   Cashew Fudge  
2        waffels  
3   Carrot Halwa

In [87]:
# 23. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
import pandas as pd
studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']})
df = pd.DataFrame(studentData)

print(df)
# Sort by Nmae
df.sort_values(by = ['Name'], inplace = True)
print("\ndf sorted by Name ...\n", df)
# Sort by address
df.sort_values(by = ['address'], inplace = True)
print("\ndf sorted by address ...\n", df)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

df sorted by Name ...
       Name  Height Qualification  address  Age        Pets           sport
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball

df sorted by address ...
       Name  Height Qualification  address  Age        Pets           sport
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21   

In [8]:
# 24. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
import pandas as pd
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
print(df)

df.to_csv(r'C:\Users\timje\Code\SavvyCoders\homework\cows_and_goats.csv')


        Cows  Goats
Year 1    12     22
Year 2    20     19


In [15]:
# 25. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name

import pandas as pd 

Vegetables = pd.DataFrame([["Cauliflower", "Flower", "White"], ["Spinach", "Leafy", "Green"], ["Potato", "Tubert", "Yellow"]], 
                        columns=["List", "Type", "Color"])
Vegetables
Vegetables.to_csv('vegetables.csv')
print(Vegetables)
Vegetables.to_csv(r'C:\Users\timje\Code\SavvyCoders\homework\Vegetables.csv')

Vegetables['Color'] = Vegetables['Color'].replace({'Yellow': 'Red'})
Vegetables.to_csv("Vegetables.csv", index=False)
print(Vegetables)

Vegetables.to_csv(r'C:\Users\timje\Code\SavvyCoders\homework\NewVegetables.csv')

          List    Type   Color
0  Cauliflower  Flower   White
1      Spinach   Leafy   Green
2       Potato  Tubert  Yellow
          List    Type  Color
0  Cauliflower  Flower  White
1      Spinach   Leafy  Green
2       Potato  Tubert    Red


# 1. What does Pandas stand for?
# Panel Data,which is a Python Data Analysis Library

# 2. What are the 2 collections used in Pandas?
# the 2 collections are: Series and Dataframes

# 3. Name 4 things Pandas can do for us.
# Data Cleansing, Data Normalization, Data Inspection, and Data Fill

# 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
# Values
# 5. What is a CSV
# CSV stands for Comma-Separated Values which is a type of data file that contains plain text and is a well know format that can be read by everyone including Pandas.

# 6. When cleaning data what values do we not like in our data
# Null Values